version: "3.8"

services:
  api_neo4j:
    container_name: api.neo4j
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    depends_on:
      - db_neo4j

  db_neo4j:
    container_name: database.neo4j
    image: neo4j:5.11-enterprise
    restart: unless-stopped
    ports:
      - '7687:7687'
    volumes:
      - data:/data
      - logs:/logs
      - import:/import
    environment:
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/initial_password123

volumes:
  data:
  logs:
  import:
