version: "3.8"

services:
  api_postgres:
    container_name: api.postgres
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    depends_on:
      - db_postgres

  db_postgres:
    container_name: database.postgres
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.local

volumes:
  postgres_data:
