version: "3.8"

services:
  api_neo4j:
    container_name: api.neo4j
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    depends_on:
      - db_neo4j

  db_neo4j:
    container_name: database.neo4j
    image: neo4j:5.11-enterprise
    ports:
      - '7687:7687'
    volumes:
      - data:/data
      - logs:/logs
      - import:/import
      - plugins:/plugins
    environment:
      - EXTENDED_CONF=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/initial_password123
      - NEO4J_PLUGINS=["apoc-extended", "apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

volumes:
  data:
  logs:
  import:
  plugins:
